###### !/usr/env/bin python
# -*- coding: utf-8 -*-
# Generated by Selenium IDE
import urllib.request
#import chardet
from ntpath import join
import pytest
import time
from datetime import datetime as dt
import re
import json
import shutil
import os
import glob
import pandas as pd
import numpy as np
from logging import getLogger, StreamHandler, Formatter, FileHandler, DEBUG
import datetime
from datetime import timedelta
from datetime import datetime as dt
from styleframe import StyleFrame
import PySimpleGUI as sg
import pprint
from selenium import webdriver
import chromedriver_binary
from webdriver_manager.chrome import ChromeDriverManager
#マネージメントﾄﾞﾗｲﾊﾞｰ設定
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
# /* ------- 追加部分 -------
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
# -------------------------*/
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.alert import Alert
#from PyPDF2 import PdfFileReader
#import fitz
#import pdfminer

#from pypdf import dfReader
import tabula
#from pypdf import PdfReader
class Ifs_base():
    def __init__(self, parent=None):
        self.log_in_data=["s.miya@screen-cas.co.jp","upd8253a-190"]
        self.driverf=[] 
        self.log_folder = '{0}.log'.format(datetime.date.today())
        self.logger = self.setup_logger(self.log_folder)
        self.d = {'fukatsu@screen.co.jp':'深津 英司',
                  'shinjo@screen.co.jp':'新庄 淳一',
                  'ku.yamamoto@screen.co.jp':'山本 邦晴',                  
                  'k.kawaguchi@screen.co.jp':'川口 賢士',                  
                  's.urata@screen.co.jp':'浦田 真吾',                  
                  'hir.taniguchi@screen.co.jp':'谷口 寛樹',                  
                  'terakawa@screen.co.jp':'寺川 知宏',                  
                  'n.iwasaki@screen.co.jp':'岩﨑 法一',                  
                  'mochida@screen.co.jp':'持田 哲平',                  
                  'masakazu@screen-cas.co.jp':'田中 正和',                  
                }                  
    def setup_method(self):
#        self.driver = webdriver.Chrome('C:\chrome_data\chromedriver.exe')
        self.vars = {}
        self.log_folder = '{0}.log'.format(datetime.date.today())
        self.defult_dir=os.path.dirname(os.path.abspath(__file__))
        self.logger = self.setup_logger(self.log_folder)
        self.next_step=False

    def setup_logger(self,log_folder, modname=__name__):
        logger = getLogger(modname)
        logger.setLevel(10)
    
        sh = StreamHandler()
        sh.setLevel(10)
        formatter = Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        sh.setFormatter(formatter)
        logger.addHandler(sh)
    
        fh = FileHandler(log_folder) #fh = file handler
        fh.setLevel(DEBUG)
        fh_formatter = Formatter('%(asctime)s - %(filename)s - %(name)s - %(lineno)d - %(levelname)s - %(message)s')
        fh.setFormatter(fh_formatter)
        logger.addHandler(fh)
        return logger
    #ログイン
    def log_in(self,driver,log_in_data):
        self.logger.debug('LOG IN')
        login_id = driver.find_element(By.NAME, "os_username")
        login_id.send_keys(log_in_data[0])
        time.sleep(1)
        # パスワードを入力
        password = driver.find_element(By.NAME,"os_password")
        password.send_keys(log_in_data[1])
        #ログインボタンをクリック
        login_btn = driver.find_element(By.NAME,"login")
        login_btn.click()

    def check_setup_file_exist(self,file_name,item_list):
        """設定ファイル：ない場合は作
        Args:
            filename (_type_): 設定ファイルの名前　拡張子Xlsx
            item_list (_type_): 設定ファイルの項目

        Returns:
            df: _設定ファイルの内容_
        """
        self.defult_dir=os.path.dirname(os.path.abspath(__file__)).replace('\\','/')
        if not os.path.isfile(file_name):#ファイルがない場合
            cols = ['file_dir','file_name','file_path']#colunmの項目
#            ind=['SCM登録_台帳','SCM管理シート','SCMデータ','ZIPファイル','SCMリスト']
#            df = pd.DataFrame(index=ind, columns=cols)
            df = pd.DataFrame(index=item_list, columns=cols)
            for i in range(len(item_list)):
                df.loc[item_list[i],'file_dir']=self.defult_dir
                df.loc[item_list[i],'file_name']='未設定'
                df.loc[item_list[i],'file_path']='未設定'
                self.logger.debug(df)
                df.to_excel(file_name,index=True)
        else:#ある場合
            df=pd.read_excel(file_name, index_col=0)
            print(df)
            for i in range(len(df)):
                if pd.isna(df.loc[i,'file_dir']):
                    df.loc[i,'file_dir']=self.defult_dir
                    df.to_excel(file_name,index=True,encoding="SHIFT-JIS")
                elif not os.path.isdir(df.loc[i,'file_dir']):
                    df.loc[i,'file_dir']=self.defult_dir
                    df.to_excel(file_name,index=True,encoding="SHIFT-JIS")
        colunms_pos=0
        sheetname=0
        item_width=[40,50,40,40]
        self.write_excel_parts(file_name,colunms_pos,sheetname,item_list,item_width)

        return df
    def trans_list(self,file_path1,file_path2):
        df=pd.read_excel(file_path1)
        df_para=pd.read_excel(file_path2)
        df=df[df.loc['担当者(機械)']==df_para.loc['メールアドレス']]


        return df




#################################
#  csvファイルを読む。
    def read_csv(self,file_path,colunms_pos):

        df=pd.read_csv(file_path,header=colunms_pos)
        return df
################################
# 入力：df データフレーム
#      item_list 抽出する項目
# 出力：df データフレーム（項目を抽出した。））　　　   
    def read_parts(self,df,item_list):
#        print([item for item in item_list])
        df=df[[item for item in item_list]]
        return df
##################################################    
# 入力：file_path　ファイルパス
# 　　　colunms_pos　コラムの行
# 　　　item_list　　抽出したい項目リスト
# 　　　item_width)　抽出したい項目リストの幅
# 出力：エクセルファイル
##################################################
    def write_parts(self,file_path,colunms_pos,item_list,item_width):
        df=pd.read_csv(file_path,header=colunms_pos,encoding="cp932")
        
        df=df[[item for item in item_list]]#item_listに記載されている項目だけのファイルを作成する。
        df.to_excel(file_path[:-4]+'.xlsx')
        with StyleFrame.ExcelWriter(file_path[:-4]+'.xlsx') as writer:
            sf=StyleFrame(df)
#            for item in item_list:
            for (item,iten_width) in zip(item_list,item_width):
                sf.set_column_width(columns=[item], width=iten_width)
#            sf.set_row_height(rows=list(range(2, len(df_jira_list)+2)), height=40)
            sf.to_excel(writer, index=False)
        return df
    
    def write_csv_part(self,file_path,colunms_pos,item_list,item_width):
        df=pd.read_csv(file_path,header=colunms_pos,encoding="cp932")
#        df=pd.read_csv(file_path,header=colunms_pos,encoding="Shift-Jis")
        
        df=df[[item for item in item_list]]#item_listに記載されている項目だけのファイルを作成する。
        df.to_excel(file_path[:-4]+'.xlsx')
        with StyleFrame.ExcelWriter(file_path[:-4]+'.xlsx') as writer:
            sf=StyleFrame(df)
#            for item in item_list:
            for (item,iten_width) in zip(item_list,item_width):
                sf.set_column_width(columns=[item], width=iten_width)
#            sf.set_row_height(rows=list(range(2, len(df_jira_list)+2)), height=40)
            sf.to_excel(writer, index=False)
        return df 

    def write_excel_part(self,file_path,colunms_pos,item_list,item_width):

        df=pd.read_excel(file_path,header=colunms_pos)
#        df=pd.read_csv(file_path,header=colunms_pos,encoding="Shift-Jis")
        
        df=df[[item for item in item_list]]#item_listに記載されている項目だけのファイルを作成する。
        df.to_excel(file_path[:-5]+'.xlsx')
        with StyleFrame.ExcelWriter(file_path[:-4]+'.xlsx') as writer:
            sf=StyleFrame(df)
#            for item in item_list:
            for (item,iten_width) in zip(item_list,item_width):
                sf.set_column_width(columns=[item], width=iten_width)
#            sf.set_row_height(rows=list(range(2, len(df_jira_list)+2)), height=40)
            sf.to_excel(writer, index=False)
        return df     



##################################################    
# 入力：file_path　ファイルパス
# 　　　colunms_pos　コラムの行
# 　　　item_list　　抽出したい項目リスト
# 　　　item_width)　抽出したい項目リストの幅
# 出力：エクセルファイル
    def write_excel_parts(self,file_path,colunms_pos,mode,sheet_name,item_list,item_width):
        df=pd.read_excel(file_path,header=colunms_pos,sheet_name=sheet_name)
        df=df[[item for item in item_list]]#item_listに記載されている項目だけのファイルを作成する。
#        with StyleFrame.ExcelWriter(file_path[:-5]+'xxx.xlsx') as writer:
        with StyleFrame.ExcelWriter(file_path) as writer:
            sf=StyleFrame(df)
#            for item in item_list:
            for (item,iten_width) in zip(item_list,item_width):
                sf.set_column_width(columns=[item], width=iten_width)
#            sf.set_row_height(rows=list(range(2, len(df_jira_list)+2)), height=40)
            sf.to_excel(writer, index=False)
        return file_path
            
###############################################
#
    def analisis(self,file_path,key_word,item_list,item_width):
        df=pd.read_excel(file_path,header=0)
        df_a=df.columns
#        print(df_a)
#        df_a=pd.concat([df.iloc[3:8,:],df.iloc[1:3,:]],axis=0)
#        print(df_a)        

#        print(len(df))
        lengh=len(df)
        add_flag=0
        df_a=df.iloc[0:1,:]
        for i in range(lengh):
#            print('n=',i,'  ',df.loc[i,'品名'],' ',type(df.loc[i,'品名']))
#            print(df.loc[i,'品名'].isnull().all())
#######セルが文字の時
            if isinstance(df.loc[i,'品名'],str):
#                print(df.loc[i,'品名'])
# 
                if key_word in df.loc[i,'品名'] :
                    print('n=',i,df.loc[i,'品名'])
                    add_flag=1
                if '68P' in df.loc[i,'親品目ｺｰﾄﾞ'] :
                    df_a=pd.concat([df_a,df.iloc[i:i+1,:]],axis=0)
                    print('n=',i,df.loc[i,'品名'])
                    add_flag=0

            if add_flag==1:
                df_a=pd.concat([df_a,df.iloc[i:i+1,:]],axis=0)
#            print(df_a)
#            print(len(df_a))
        print(df_a)
        print(len(df_a))

        with StyleFrame.ExcelWriter(file_path[:-5]+'_sel.xlsx') as writer:
            sf=StyleFrame(df_a)
#            for item in item_list:
            for (item,iten_width) in zip(item_list,item_width):
                sf.set_column_width(columns=[item], width=iten_width)
#            sf.set_row_height(rows=list(range(2, len(df_jira_list)+2)), height=40)
            sf.to_excel(writer, index=False)


#        df_a.to_excel(file_path[:-5]+'_sel.xlsx',index=False)

    def count_6V(self,file_path):
        df=pd.read_csv(file_path,encoding="shift-jis")
        df_csv=df.fillna('-')
        n_6v9=df_csv[df_csv["親品目ｺｰﾄﾞ"].str.contains('6V9')]
        n_6vC=df_csv[df_csv["親品目ｺｰﾄﾞ"].str.contains('6VC')]
        print(len(n_6v9), len(n_6vC))
        
    def display(self):
        sg.theme('DarkAmber')
        layout = [  [sg.Text('部品表作成')],
            [sg.Text('ファイル', size=(15, 1)), sg.Input(), sg.FileBrowse('ファイルを選択', key='inputFilePath')],
            [sg.Button('作成'), sg.Button('キャンセル')] ]
        window = sg.Window('サンプルプログラム', layout)
        while True:
            event, values = window.read()
            if event == sg.WIN_CLOSED or event == 'キャンセル':
                break
            elif event == '作成':
                colunms_pos=0
                item_list=['ﾚﾍﾞﾙ','子品目ｺｰﾄﾞ','品名','規格/型番','数量_','製造中止ﾌﾗｸﾞ','使用不可ﾌﾗｸﾞ']
                item_width=[8,15,36,36,8,8,8]

                myclass.write_parts(values['inputFilePath'],colunms_pos,item_list,item_width)
                print('部品表作成 ',values['inputFilePath'])

        window.close()

    def display2(self):
        sg.theme('DarkAmber')
        layout = [  [sg.Text('カタログ')],
            [sg.Text('ファイル', size=(15, 1)), sg.Input(), sg.FileBrowse('ファイルを選択', key='inputFilePath')],
            [sg.Button('作成'), sg.Button('キャンセル')] ]
        window = sg.Window('サンプルプログラム', layout)
        while True:
            event, values = window.read()
            if event == sg.WIN_CLOSED or event == 'キャンセル':
                break
            elif event == '作成':
                colunms_pos=0
#                item_list=['ﾚﾍﾞﾙ','子品目ｺｰﾄﾞ','品名','規格/型番','数量_','製造中止ﾌﾗｸﾞ','使用不可ﾌﾗｸﾞ']
                item_list=['品目番号','規格/型番','子ﾌﾟﾛｼﾞｪｸﾄ番号','ﾌﾟﾛｼﾞｪｸﾄ製品名','最終納入先名称','最上位設計品目']
#                item_width=[8,15,36,36,8,8,8]
                item_width=[15,20,20,15,50,15]
                myclass.write_parts(values['inputFilePath'],colunms_pos,item_list,item_width)
                print('部品表作成 ',values['inputFilePath'])

        window.close()
        
    def make_base_file(self,base_url,driver,dir,flage):
        #部品問合せ対策 
        if flage==1:
            self.driver.get(base_url)
        else:
            self.driver=driver
        time.sleep(2)

        self.driver.find_element(By.ID, "AJS_DROPDOWN__82").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "allExcelFields").click()
        time.sleep(20)
        self.logger.debug("end")
    ########
    # ダウンロードﾌｫﾙﾀﾞｰにあるエクセルファイルを利用できる形にすうｒ。
    ########
        download_dir=r'C:\Users\AA004011\Downloads'
        xls_dir=os.path.join(download_dir,r'*.xls')
        time.sleep(2)
        st=True
        while st:
            xls_files = glob.glob(xls_dir)
            if xls_files!=[]:
                self.logger.debug(xls_files)
                time.sleep(1)
                st=False
        self.logger.debug(xls_files)
    #s_file: ダウンロードにあるファイルの名称がリストである。
    #複数個あったZIPファイルのうち、一番最近のZIPを選択
        self.logger.debug(len(xls_files))
        s_file=xls_files[0]
        self.logger.debug('s_file='+s_file)
    #        self.logger.debug('uuu',s_file)
    # XLSファイルの読み込み
    #        wb = openpyxl.load_workbook(path)
    #        book = xlrd.open_workbook(path)
    # XLSファイル（実際はHTMLファイル）テーブルをDataFrameとして読み込む
    #        s_file=r'C:\Users\AA004011\Downloads\SU改造見積未回答リスト＿枚葉＿ (SEEWP JIRA) 2023-03-05T18_06_14+0900.xls'
        print(s_file)
#        wb = xw.Workbook(s_file[:-4].h)
#        wb.save(s_file+'xlsx')
    
        df = pd.read_html(s_file)
        file_path=s_file+'.xlsx'
#        self.logger.debug(df[0])
#        self.logger.debug(df[1])     
        self.logger.debug('file_path='+file_path)

#        file_path=r'C:テスト220708.xls.xlsx'        
        df[1].to_excel(file_path, index=False)
        self.logger.debug('dir='+dir)
        file_path=shutil.move(file_path,dir)
        os.remove(s_file)#不要になったファイルをダウンロードフォルダーから消す
        #baseファイルのpathを渡す。
        return file_path
    def buhin_toi(self,url,dir):
        self.driver = webdriver.Chrome('C:\chrome_data\chromedriver.exe')
        self.driver.get(url)
        time.sleep(3)
        link_elem=self.driver.find_element(By.TAG_NAME, 'a').get_attribute('href')      
        print(link_elem)
        self.driver.get(link_elem)
        # ログインIDを入力
        self.log_in(self.driver,self.log_in_data)        
        time.sleep(3)
        file_path=myclass.make_base_file(url,self.driver,dir,0)
        a=1
    def tanto(self,file_path,sheet_name):
        df=pd.read_excel(file_path, sheet_name='枚葉',index_col=None)
        print(df)
        length=len(df)
        for i in range(length):
            x=df.loc[i,"担当者(機械)"]
            print(x)
            df.loc[i,'担当者(機械)']=self.d[df.loc[i,'担当者(機械)']]
            df.loc[i,'照査(機械)']=self.d[df.loc[i,'照査(機械)']]
            df.loc[i,'承認(機械)']=self.d[df.loc[i,'承認(電気)']]
            df.loc[i,'担当者(電気)']=self.d[df.loc[i,'担当者(電気)']]
            df.loc[i,'照査(電気)']=self.d[df.loc[i,'照査(電気)']]
            df.loc[i,'承認(電気)']=self.d[df.loc[i,'承認(電気)']]
        print(df)
        df.to_excel(file_path[:-4]+'名前.xlsx',index=False)
        colunms_pos=0
        item_list=['顧客','顧客番号','担当者(機械)','照査(機械)','承認(機械)','担当者(電気)','照査(電気)','承認(電気)']
        item_width=[30,15,20,20,20,20,20,20]
        file_path=file_path[:-4]+'名前.xlsx'
        self.write_excel_parts(file_path,colunms_pos,sheet_name,item_list,item_width)

    def opetator(self,file_path,sheet_name):
        sheet_name_list=['枚葉','インテグ','バッチ']
        mode_list=['','a','a']
        for j in range(len(sheet_name_list)):
            mode=mode_list[j]
            df=pd.read_excel(file_path, sheet_name=sheet_name_list[j],index_col=None)
            df_para=pd.read_excel(file_path, sheet_name='名前',index_col=0)
            d = df_para.to_dict(orient='dict')

            print(df)
            length=len(df)
            for i in range(length):
                x=df.loc[i,"担当者(機械)"]
                print(x)
                df.loc[i,'担当者(機械)']=d['メールアドレス'][df.loc[i,'担当者(機械)']]

                df.loc[i,'照査(機械)']=d['メールアドレス'][df.loc[i,'照査(機械)']]
                df.loc[i,'承認(機械)']=d['メールアドレス'][df.loc[i,'承認(電気)']]
                df.loc[i,'担当者(電気)']=d['メールアドレス'][df.loc[i,'担当者(電気)']]
                df.loc[i,'照査(電気)']=d['メールアドレス'][df.loc[i,'照査(電気)']]
                df.loc[i,'承認(電気)']=d['メールアドレス'][df.loc[i,'承認(電気)']]
            print(df)
            #sheet_name=sheet_name_list[j]
            df.to_excel(file_path[:-4]+'メールアドレス.xlsx',mode,sheet_name=sheet_name_list[j],index=False)
            colunms_pos=0
            item_list=['顧客','顧客番号','担当者(機械)','照査(機械)','承認(機械)','担当者(電気)','照査(電気)','承認(電気)']
            item_width=[30,15,30,30,30,30,30,30]
            file_path_w=file_path[:-4]+'メールアドレス.xlsx'
            sheet_name=sheet_name_list[j]
            self.write_excel_parts(file_path_w,colunms_pos,mode,sheet_name,item_list,item_width)

    def joint_file(self,file_path_master,joint_list,dir):
        """IFSで任意の部品がt使われている製番一覧ファイル(cSV)
        を結合する。

        Args:
            file_path_master (_type_):結合したファイルのPath
            joint_list (_type_):結合するファイルのリスト 
            dir (_type_): 操作するフォルダー
        """        
        for file_name_csv in joint_list:
            file_path=os.path.join(dir,file_name_csv+'.csv')
            df=pd.read_csv(file_path,header=0)
#            print(df)
            if file_name_csv==joint_list[0]:
                df_master=df
            else:
                df_master=pd.concat([df_master,df])
            print(file_name_csv,'データ数',len(df))
        item_list= ['品目番号','品名','ﾌﾟﾛｼﾞｪｸﾄ名称','子ﾌﾟﾛｼﾞｪｸﾄ番号','最終納入先名称','最上位設計品目']
        df_master=df_master[[item for item in item_list]]
        df_master.to_excel(file_path_master,index=False)
        colunms_pos=0
        item_width=[20,30,20,20,30,20]
        mode=0
        sheet_name='Sheet1'
        self.write_excel_parts(file_path_master,colunms_pos,mode,sheet_name,item_list,item_width)
    def check(self,df):

# 連番列を取得
        sequence_column = df['子ﾌﾟﾛｼﾞｪｸﾄ番号']

# 最小値と最大値の間のすべての番号を生成
        all_numbers = set(range(sequence_column.min(), sequence_column.max() + 1))

# 実際の列に存在しない番号を抽出
        missing_numbers = all_numbers - set(sequence_column)
        print(missing_numbers)



    def bind(self,folder_path):

        csv_files=[f for f in os.listdir(folder_path) if f.endswith('.csv')]
        chardet.detect(rawdata)
        combinded_df=pd.concat([pd.read_csv(os.path.join(folder_path,file)) for file in csv_files],ingnore_index=True)
        print(combinded_df)
        combinded_df.to_excel('combinded_excel.xlsx')

    def read_pdf(self,file_path,file_path2):
# PDFファイルの読み込み
        reader = PdfReader(file_path)

# ページ数の取得
        number_of_pages = len(reader.pages)

# ページの取得。この場合は、1ページ目を取得する。
        page = reader.pages[0]

# テキストの抽出
        text = page.extract_text()

        csv_file="'"+text.replace( "\n","','")+"\n"


        with open(file_path2, mode='w',encoding='utf_8') as f:
            f.write(csv_file)
        df=pd.read_table(file_path2,sep=',')
        print(df)
        df.to_excel(file_path2[:-4]+'.xlsx')
        
    def read_pdf_table(self,file_path,file_path2):
        dfs = tabula.read_pdf(file_path,lattice=True)
        for df in dfs:
            print(df)
            df.to_excel(file_path2,index=False)
    def read_kintai(self,url):
        dfs = pd.read_html(url)
        print(dfs)
        

def main():
    myclass=Ifs_base()
    a=1
    url=r'https://kintai.digisheet.com/'
    myclass.read_kintai(url)


    dir=r'C:\Users\AA004011\OneDrive - SCREEN Holdings Co., Ltd\☆'
    file_name=r'moo1012269378181397-6-20231129-1702469786040.pdf'
    file_path=os.path.join(dir,file_name)
    file_name=r'書き出しデータ.xlsx'
    file_path2=os.path.join(dir,file_name)
#    myclass.read_pdf(file_path,file_path2)
    myclass.read_pdf_table(file_path,file_path2)

    dir=r'C:\Users\AA004011\OneDrive - SCREEN Holdings Co., Ltd\☆パーツ検討\製品問合せ伝助\DEN_PR-3729_【緊急】63917698（ﾌﾟﾗｯﾄﾎｰﾑｲﾝﾀｰﾛｯｸｷﾊﾞﾝ4）生産中止に伴う代替品目確認依頼\品目カタログ\品目カタログ'
    file_name=r'ﾌﾟﾗｯﾄﾎｰﾑｲﾝﾀｰﾛｯｸｷﾊﾞﾝ製番一覧.xlsx'
    file_path=os.path.join(dir,file_name)
    joint_list=['63911980.csv','63913469.csv','63917698.csv','63922897.csv','63924088.csv','63924938.csv','63925880.csv','63937615.csv']
#    myclass.joint_file(file_path,joint_list,dir)


    url=r'https://seewp.screen.co.jp/jira/issues/?filter=107993'
#    file_path=myclass.buhin_toi(url,dir)
#    file_name=r'部品問い合わせ伝助 (SEEWP JIRA) 2023-12-21T10_47_19+0900.xls.xlsx'

    file_name=r'JIRA担当者_名前表記_231228.xlsx'
    file_path=os.path.join(dir,file_name)
    item_width=[30,15,20,50,28,20,20,30,40,40]
    colunms_pos=0
    item_list=['作成日','ラベル','キー','要約','機種名','ステータス','担当者','報告者','電気設計(仕様) 回答ステータス','電気設計(見積) 回答ステータス',]
#    myclass.write_excel_parts(file_path,colunms_pos,item_list,item_width)
    dir=r'C:\Users\AA004011\OneDrive - SCREEN Holdings Co., Ltd\☆JIRA受付\担当者'
    file_name='JIRA担当者_231227_rev15.xlsx'
    file_name=r'JIRA担当者_名前表記_231228.xlsx'
    file_path=os.path.join(dir,file_name)
    sheet_name='枚葉'
    #'枚葉'
#    myclass.opetator(file_path,sheet_name)
######################################################################################    
    item_list=['改造伝助_操作','SU改造伝助_記録','バッチ改造伝助_記録','担当者リスト','JIRA受付ディレクトリ']
    file_name='DEN_data.xlsx'
#    myclass.check_setup_file_exist(file_name,item_list)
    




if __name__ == "__main__":
    myclass=Ifs_base()
    main()