###### !/usr/env/bin python
# -*- coding: utf-8 -*-
# Generated by Selenium IDE
import urllib.request
import chardet
from ntpath import join
import pytest
import time
###### !/usr/env/bin python
# -*- coding: utf-8 -*-
# Generated by Selenium IDE
import pytest
import time
from datetime import datetime as dt
import re
import json
import shutil
import os
import glob
import pandas as pd
import numpy as np
import ライブラリ as lib
import PySimpleGUI as sg
#import FreeSimpleGUI as sg
class x_base():
    def __init__(self, parent=None):
        self.log_in_data=["s.miya@screen-cas.co.jp","upd8253a-190"]

#  csvファイルを読む。
    def read_csv(self,file_path,colunms_pos):

        df=pd.read_csv(file_path,header=colunms_pos)
        return df
    
    def View_csv_xlsx(self):

        layout = [
   [sg. Text("ファイル"), sg.InputText(), sg.FileBrowse(key="file1")],
   [sg.Submit(), sg.Cancel()],
]

        layout = [
            
            [sg.Text("フォルダを選択"),
            sg.InputText(), sg.FileBrowse('ファイル読込', target='-file-', file_types=(('Excell ファイル', '*.csv'),))],
            [sg.Text("ファイルを選択"),
            sg.InputText(), sg.FileBrowse(key="file1")],
            [sg.Submit("送信",sg.Cancel("キャンセル"))]
            ]



        window = sg.Window('ファイルの選択', layout)

        while True:
            event, value = window.read()  # イベントの入力を待つ

            if event == '-Btn-':
                message = '選択したファイルの絶対パスは、' + value['-File_path-'] + 'です'
                sg.popup(message)
                break
            elif event is None:
                break
        window.close()
####################################################################################################3
    def csv_xlsx_change(self):
        layout = [[sg.Text('ファイル選択'),
                   sg.InputText('ファイルパス・名',key='-file-'),
                   sg.FilesBrowse('ファイル読込', target='-file-', file_types=(('Excell ファイル', '*.csv'),))],
                 [sg.Radio("順展開", "radio_group", default=True), sg.Radio("逆展開", "radio_group"), sg.Radio("カタログ", "radio_group"), sg.Radio("製番", "radio_group"),sg.Radio("品目検索", "radio_group"),sg.Radio("選択品目部品表展開結果", "radio_group"),sg.Radio("差分", "radio_group"),sg.Radio("一覧プロジェクト", "radio_group"),sg.Radio("一覧設品目更新", "radio_group"),sg.Radio("差分情報紹", "radio_group")],
                 [sg.Button('実行',key='bt')]]
      # ウィンドウの作成
        window = sg.Window("CSV - Xlsx変換", layout)   
      # イベントループ
        while True:
             event, values = window.read()
             if event in (None, "キャンセル"):
                 break
             if event == "bt":
              # 選択されたファイルを表示 '-file-'がキーワード
                file_path = values['-file-']
                print(file_path)
                print(values[0])
                print(values[1])
                print(values[2])
                print(values[3])
                if values[0]:#順展開
                    list = ['ﾚﾍﾞﾙ',10,'順序',10,'子品目ｺｰﾄﾞ',20,'品名',30,'規格/型番',40,'ﾒｰｶ名',30,'数量_',10,'製造中止ﾌﾗｸﾞ',10,'使用不可ﾌﾗｸﾞ',10,'使用不可ﾌﾗｸﾞ更新日',20]
                if values[1]:#逆展開
                    list = ['ﾚﾍﾞﾙ',10,'順序',10,'親品目ｺｰﾄﾞ',20,'品名',30,'規格/型番',40,'数量_',10,'作成日',20,'更新日',20,'製造中止ﾌﾗｸﾞ',10,'使用不可ﾌﾗｸﾞ',10,'使用不可ﾌﾗｸﾞ更新日',20]
                if values[2]:#カタログ
                    list = ['品目番号',15,'品名',30,'規格/型番',40,'子ﾌﾟﾛｼﾞｪｸﾄ番号',20,'機種ｺｰﾄﾞ',10,'集計用機種名称',20,'工場出荷日',20,'最終納入先名称',40,'最上位設計品目',15,'使用個数_',10] 
                if values[3]:#製番
                    list = ['子ﾌﾟﾛｼﾞｪｸﾄ番号',20,'ﾌﾟﾛｼﾞｪｸﾄ説明',70,'PJ種別',10,'PJ分類',10,'機種ｺｰﾄﾞ',10,'機種名',20,'最終納入先名称',40,'最上位設計品目',15,'工場出荷日',20]
                if values[4]:#品目検索
                    list = ['品目ｺｰﾄﾞ',20,'品名',30,'規格/型番',40,'作成日',20,'更新日',20,'製造中止ﾌﾗｸﾞ',10,'使用不可ﾌﾗｸﾞ',10]
                if values[5]:#選択品目部品表展開結果
                    list = ['[ﾚﾍﾞﾙ]',10,'[順序]',10,'[品目ｺｰﾄﾞ]',20,'[品名]',30,'[規格/型番]',40,'[数量]_',20,'[製造中止ﾌﾗｸﾞ]',10,'[使用不可ﾌﾗｸﾞ]',10] 
                if values[6]:#差分
                    list = ['No._',10,'内容',10,'ﾚﾍﾞﾙ',10,'順序',10,'子品目ｺｰﾄﾞ',20,'品名',30,'規格/型番',40]
                if values[7]:#一覧プロジェクト
                    list = ['子ﾌﾟﾛｼﾞｪｸﾄ番号',15,'ﾌﾟﾛｼﾞｪｸﾄ説明',50,'機種名',20,'工場出荷日',20,'最終納入先名称',30,'最上位設計品目',20]
                if values[8]:#一覧設計品目更新
                    list = ['品目ｺｰﾄﾞ',20,'品名',30,'規格/型番',40,'ﾒﾓ',60,'作成日',20,'更新日',20,'製造中止ﾌﾗｸﾞ',10,'使用不可ﾌﾗｸﾞ',10]
                if values[9]:#差分情報紹介
                    list = ['内容',20,'子品目ｺｰﾄﾞ',40,'品名',30,'規格/型番',60]
                if values[10]:#フォルダーにあるCSVファイルをXlsxファイルに変換
                    list = ['内容',20,'子品目ｺｰﾄﾞ',40,'品名',30,'規格/型番',60]

                colunms_pos=0
                item_list=list[0::2]
                item_width=list[1::2]
                print(item_list)
                print(item_width)
                myclass.write_csv_part(file_path,colunms_pos,item_list,item_width)
                sg.popup(f"選択されたフォルダ: {file_path}")     
        window.close()
    def make_hinmoku_touroku(self,list_file_path,original_file_path,dir):
        df=pd.read_excel(list_file_path,header=3)
        print(df)

#        for j in range(12):
#            folder_name=str(int(df.loc[j,'品目ｺｰﾄﾞ.2']))+'('+df.loc[j,'品名.2']+'_'+df.loc[j,'規格/型番.2']+')'
#            print(folder_name)
#            file_path_dist=os.path.join(dir,folder_name)
#            file_path_dist=shutil.copytree(original_file_path, file_path_dist)

        for j in range(8):
            folder_name=str(int(df.loc[j,'品目ｺｰﾄﾞ.3']))+'('+df.loc[j,'品名.3']+'_'+df.loc[j,'規格/型番.3']+')'
            print(folder_name)
            file_path_dist=os.path.join(dir,folder_name)
            file_path_dist=shutil.copytree(original_file_path, file_path_dist)

        for j in range(12):
            folder_name=str(int(df.loc[j,'品目ｺｰﾄﾞ.4']))+'('+df.loc[j,'品名.4']+'_'+df.loc[j,'規格/型番.4']+')'
            print(folder_name)
            file_path_dist=os.path.join(dir,folder_name)
            file_path_dist=shutil.copytree(original_file_path, file_path_dist)

    def list_csv_files(self,folder_path):
        csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
        return csv_files

    def csv_xlsx(self,dir,list):
        for i in range(len(list)):
#            file_name=list[i]+'.csv'
            file_name=list[i]
            file_path=os.path.join(dir,file_name)
            df=pd.read_csv(file_path)
            list=df.columns
            print(list)
            for ifs_list[i] in range(len(ifs_list)):
                print(set(ifs_list[i]).issubset(list))



            colunms_pos=0
            item_list=['ﾚﾍﾞﾙ','順序','子品目ｺｰﾄﾞ','品名','規格/型番','数量_','製造中止ﾌﾗｸﾞ','使用不可ﾌﾗｸﾞ']
#            item_list=['品目番号','品名','規格/型番','子ﾌﾟﾛｼﾞｪｸﾄ番号','機種名','最終納入先名称','最上位設計品目']            
            item_width=[10,20,30,30,50,20]
#            item_width=[20,30,30,30,30,50,20]            
            myclass.write_csv_part(file_path,colunms_pos,item_list,item_width)

    def csv_xlsx2(self,dir,list,sel):
        for i in range(len(list)):
#            file_name=list[i]+'.csv'
            file_name=list[i]
            file_path=os.path.join(dir,file_name)
            match sel:
                case '品目カタログ':
                    item_list=['品目番号','品名','規格/型番','子ﾌﾟﾛｼﾞｪｸﾄ番号','機種名','工場出荷日','最終納入先名称','最上位設計品目']
                    item_width=[18,40,40,30,20,30,50,20]
                case '通常':
                    item_list=['ﾚﾍﾞﾙ','順序','子品目ｺｰﾄﾞ','品名','規格/型番','数量_','製造中止ﾌﾗｸﾞ','使用不可ﾌﾗｸﾞ']
            colunms_pos=0
            
#            item_list=['品目番号','品名','規格/型番','子ﾌﾟﾛｼﾞｪｸﾄ番号','機種名','最終納入先名称','最上位設計品目']            #
#            item_width=[10,20,30,30,50,20]
#            item_width=[20,30,30,30,30,50,20]            
            myclass.write_csv_part(file_path,colunms_pos,item_list,item_width)
   
def main():
    myclass=lib.Ifs_base()
    list_file_path=r'C:\Users\AA004011\OneDrive - SCREEN Holdings Co., Ltd\10-生産中止案件\20-DCP\01-DCP申請済\DCP#926_ドライバーBOXマルタイ\SU3800ドライバーBOX一覧(履歴) -MPﾄﾞﾗｲﾊﾞｰ変更.xlsx'
    original_file_path=r'C:\Users\AA004011\OneDrive - SCREEN Holdings Co., Ltd\10-生産中止案件\00-品目登録\639XXXXX(サンプル)'
    dir=r'C:\Users\AA004011\OneDrive - SCREEN Holdings Co., Ltd\10-生産中止案件\20-DCP\01-DCP申請済\DCP#926_ドライバーBOXマルタイ'

    myclass2.csv_xlsx_change()
if __name__ == "__main__":
    myclass=lib.Ifs_base()
    myclass2=x_base()  
    main()